const express=require('express')
// const registerUser=require('../controller/userController.js')
// const loginUser=require('../controller/userController.js')
const {registerUser,loginUser, getProfile, updateProfile,bookAppointment,listAppointments,cancelAppointment,paymentRazorPay,verifyRazorpay}=require('../controller/userController.js')
const authUser = require('../middleware/authUser.js')
const upload = require('../middleware/multer.js')
const userRouter=express.Router()
userRouter.post('/register',registerUser)
userRouter.post('/login',loginUser)
userRouter.get('/get-profile',authUser,getProfile)
userRouter.post('/update-profile',upload.single('image'),authUser,updateProfile)
userRouter.post('/book-appointment',authUser,bookAppointment)
userRouter.get('/appointments',authUser,listAppointments)
userRouter.post('/cancel-appointment',authUser,cancelAppointment)
userRouter.post('/payment-razorpay',authUser,paymentRazorPay)
userRouter.post('/verifyRazorpay',authUser,verifyRazorpay)
module.exports=userRouter